/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chore {
  'assignee' : Principal,
  'value' : bigint,
  'name' : string,
  'frequency' : string,
}
export interface House {
  'members' : Array<Principal>,
  'admin' : Principal,
  'name' : string,
  'currency' : string,
}
export interface HouseholdTask {
  'status' : string,
  'reward' : bigint,
  'assignedTo' : [] | [Principal],
  'isRecurring' : boolean,
  'deadline' : [] | [string],
  'taskName' : string,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Time = bigint;
export interface Transaction {
  'user' : Principal,
  'description' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface UserProfile { 'name' : string, 'houseId' : [] | [Principal] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addChore' : ActorMethod<[Principal, Chore], undefined>,
  'addHousemate' : ActorMethod<[Principal, Principal], undefined>,
  'addTask' : ActorMethod<[HouseholdTask], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeChore' : ActorMethod<[Principal, string], undefined>,
  'createHouse' : ActorMethod<[string, string], Principal>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAllTasks' : ActorMethod<[], Array<HouseholdTask>>,
  'getBalance' : ActorMethod<[Principal], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChores' : ActorMethod<[Principal], Array<Chore>>,
  'getHouse' : ActorMethod<[Principal], [] | [House]>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getTransactionHistory' : ActorMethod<[Principal], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markTaskComplete' : ActorMethod<[Principal], undefined>,
  'removeHousemate' : ActorMethod<[Principal, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'settleBalances' : ActorMethod<[Principal], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'swapChore' : ActorMethod<[Principal, string, Principal], undefined>,
  'updateChore' : ActorMethod<[Principal, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];