/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Chore = IDL.Record({
  'assignee' : IDL.Principal,
  'value' : IDL.Int,
  'name' : IDL.Text,
  'frequency' : IDL.Text,
});
export const HouseholdTask = IDL.Record({
  'status' : IDL.Text,
  'reward' : IDL.Nat,
  'assignedTo' : IDL.Opt(IDL.Principal),
  'isRecurring' : IDL.Bool,
  'deadline' : IDL.Opt(IDL.Text),
  'taskName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'houseId' : IDL.Opt(IDL.Principal),
});
export const House = IDL.Record({
  'members' : IDL.Vec(IDL.Principal),
  'admin' : IDL.Principal,
  'name' : IDL.Text,
  'currency' : IDL.Text,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const Transaction = IDL.Record({
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Int,
});

export const idlService = IDL.Service({
  'addChore' : IDL.Func([IDL.Principal, Chore], [], []),
  'addHousemate' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
  'addTask' : IDL.Func([HouseholdTask], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeChore' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'createHouse' : IDL.Func([IDL.Text, IDL.Text], [IDL.Principal], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(HouseholdTask)], ['query']),
  'getBalance' : IDL.Func([IDL.Principal], [IDL.Int], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChores' : IDL.Func([IDL.Principal], [IDL.Vec(Chore)], ['query']),
  'getHouse' : IDL.Func([IDL.Principal], [IDL.Opt(House)], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getTransactionHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTaskComplete' : IDL.Func([IDL.Principal], [], []),
  'removeHousemate' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'settleBalances' : IDL.Func([IDL.Principal], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'swapChore' : IDL.Func([IDL.Principal, IDL.Text, IDL.Principal], [], []),
  'updateChore' : IDL.Func([IDL.Principal, IDL.Text, IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Chore = IDL.Record({
    'assignee' : IDL.Principal,
    'value' : IDL.Int,
    'name' : IDL.Text,
    'frequency' : IDL.Text,
  });
  const HouseholdTask = IDL.Record({
    'status' : IDL.Text,
    'reward' : IDL.Nat,
    'assignedTo' : IDL.Opt(IDL.Principal),
    'isRecurring' : IDL.Bool,
    'deadline' : IDL.Opt(IDL.Text),
    'taskName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'houseId' : IDL.Opt(IDL.Principal),
  });
  const House = IDL.Record({
    'members' : IDL.Vec(IDL.Principal),
    'admin' : IDL.Principal,
    'name' : IDL.Text,
    'currency' : IDL.Text,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const Transaction = IDL.Record({
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Int,
  });
  
  return IDL.Service({
    'addChore' : IDL.Func([IDL.Principal, Chore], [], []),
    'addHousemate' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
    'addTask' : IDL.Func([HouseholdTask], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeChore' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'createHouse' : IDL.Func([IDL.Text, IDL.Text], [IDL.Principal], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(HouseholdTask)], ['query']),
    'getBalance' : IDL.Func([IDL.Principal], [IDL.Int], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChores' : IDL.Func([IDL.Principal], [IDL.Vec(Chore)], ['query']),
    'getHouse' : IDL.Func([IDL.Principal], [IDL.Opt(House)], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getTransactionHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTaskComplete' : IDL.Func([IDL.Principal], [], []),
    'removeHousemate' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'settleBalances' : IDL.Func([IDL.Principal], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'swapChore' : IDL.Func([IDL.Principal, IDL.Text, IDL.Principal], [], []),
    'updateChore' : IDL.Func([IDL.Principal, IDL.Text, IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };